version: "3.8"

services:
  app:
    image: docker-swimming-calculator-api:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app
  #   depends_on:
  #     - cache
  # cache:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379
  # database:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 27017:27017